name: dquery_example_app
description: A web app example for dquery.

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  dquery:
    path: ../

dev_dependencies:
  build_runner: ^2.4.1
  build_test: ^2.1.7
  build_web_compilers: ^4.0.3
